services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dashboard_sql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin1234!
    ports:
      - "1433:1433"
    restart: always
